name: train_qil
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  intl: ^0.17.0
  shared_preferences: ^2.0.13
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^5.2.1
  flutter_local_notifications: ^17.2.1
  permission_handler: ^11.3.1
  universal_html: ^2.2.4
  url_launcher: ^6.3.0
  workmanager: ^0.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  permission_handler_platform_interface: ^4.0.2

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.local
    - assets/icon.png
